services:
  postgres:
    ports:
      - "5432:5432" # expose locally so you can use TablePlus/DBeaver

  api:
    build: . # build from source locally
    env_file: .env
    ports:
      - "8080:8080" # direct access locally, no Traefik needed
