const CATEGORIES = [
    { id: 1,  name: "BCS",          name_bn: "বিসিএস",       slug: "bcs",          icon: "⭐" },
    { id: 2,  name: "Bank Jobs",    name_bn: "ব্যাংক চাকরি",  slug: "bank-jobs",   icon: "🏦" },
    { id: 3,  name: "Defense",      name_bn: "সেনাবাহিনী",     slug: "defense",     icon: "🛡️" },
    { id: 4,  name: "Police",       name_bn: "পুলিশ",         slug: "police",      icon: "👮" },
    { id: 5,  name: "Education",    name_bn: "শিক্ষা",        slug: "education",   icon: "🎓" },
    { id: 6,  name: "Health",       name_bn: "স্বাস্থ্য",     slug: "health",      icon: "⚕️" },
    { id: 7,  name: "Ministry",     name_bn: "মন্ত্রণালয়",   slug: "ministry",    icon: "🏛️" },
    { id: 8,  name: "Engineering",  name_bn: "প্রকৌশল",      slug: "engineering", icon: "⚙️" },
    { id: 9,  name: "Railway",      name_bn: "রেলওয়ে",       slug: "railway",     icon: "🚆" },
    { id: 10, name: "Others",       name_bn: "অন্যান্য",      slug: "others",      icon: "📋" }
];

const ORGANIZATIONS = [
    { id: 1,  name: "Bangladesh Bank",                    name_bn: "বাংলাদেশ ব্যাংক",              type: "bank" },
    { id: 2,  name: "Bangladesh Public Service Commission",name_bn: "বাংলাদেশ পাবলিক সার্ভিস কমিশন",type: "autonomous" },
    { id: 3,  name: "Bangladesh Army",                    name_bn: "বাংলাদেশ সেনাবাহিনী",          type: "defense" },
    { id: 4,  name: "Bangladesh Police",                  name_bn: "বাংলাদেশ পুলিশ",               type: "defense" },
    { id: 5,  name: "Ministry of Education",              name_bn: "শিক্ষা মন্ত্রণালয়",           type: "ministry" },
    { id: 6,  name: "Ministry of Health",                 name_bn: "স্বাস্থ্য মন্ত্রণালয়",       type: "ministry" },
    { id: 7,  name: "BUET",                               name_bn: "বুয়েট",                       type: "university" },
    { id: 8,  name: "Bangladesh Railway",                 name_bn: "বাংলাদেশ রেলওয়ে",             type: "autonomous" },
];

const DEMO_CIRCULARS = [
    {
        id: "c001",
        title: "Assistant Director (General)",
        organization_id: 1,
        organization_name: "Bangladesh Bank",
        category_id: 2,
        vacancy: 25,
        job_type: "permanent",
        gender: "both",
        age_min: 21,
        age_max: 35,
        education_level: "Masters",
        education_detail: "Master's degree in any discipline with minimum 2nd class",
        experience_note: "No experience required",
        salary_display: "Tk. 35,500 — 67,010 (Grade-6)",
        salary_min: 35500,
        salary_max: 67010,
        salary_grade: "Grade-6",
        location: "Anywhere in Bangladesh",
        district: null,
        published_date: "2026-06-15",
        application_deadline: "2026-07-20",
        apply_via: "online",
        apply_url: "https://bb.org.bd",
        description: "Bangladesh Bank is recruiting Assistant Directors for its various departments. Selected candidates will be responsible for policy implementation, financial analysis, and regulatory supervision of banking institutions.",
        requirements: "Master's degree in Economics, Finance, Accounting, Management, Law, or Statistics. Candidates must be Bangladeshi citizens.",
        source: "bdjobs",
        status: "active",
        is_featured: true,
        view_count: 15420
    },
    {
        id: "c002",
        title: "BCS 46th — General Education Cadre",
        organization_id: 2,
        organization_name: "Bangladesh Public Service Commission",
        category_id: 1,
        vacancy: 320,
        job_type: "permanent",
        gender: "both",
        age_min: 21,
        age_max: 30,
        education_level: "Masters",
        education_detail: "Master's degree or 4-year honors degree",
        experience_note: null,
        salary_display: "Tk. 22,000 — 53,060 (Grade-9)",
        salary_min: 22000,
        salary_max: 53060,
        salary_grade: "Grade-9",
        location: "Anywhere in Bangladesh",
        district: null,
        published_date: "2026-06-01",
        application_deadline: "2026-07-10",
        apply_via: "teletalk",
        apply_url: "http://bpsc.teletalk.com.bd",
        teletalk_code: "451",
        description: "The 46th BCS preliminary examination for General Education Cadre. This is one of the largest government recruitment exams in Bangladesh covering Assistant Professors and Lecturers for government colleges.",
        requirements: "Master's degree with at least 2nd class or CGPA 3.0 out of 4.0. Age limit 21-30 years (32 for freedom fighter quota).",
        source: "manual",
        status: "active",
        is_featured: true,
        view_count: 45230
    },
    {
        id: "c003",
        title: "Junior Officer (IT)",
        organization_id: 1,
        organization_name: "Bangladesh Bank",
        category_id: 2,
        vacancy: 40,
        job_type: "permanent",
        gender: "both",
        age_min: 21,
        age_max: 35,
        education_level: "Bachelors",
        education_detail: "B.Sc in CSE/EEE/IT or equivalent",
        experience_note: "2 years experience preferred",
        salary_display: "Tk. 22,000 — 53,060 (Grade-9)",
        salary_min: 22000,
        salary_max: 53060,
        salary_grade: "Grade-9",
        location: "Dhaka",
        district: "Dhaka",
        published_date: "2026-06-10",
        application_deadline: "2026-07-15",
        apply_via: "online",
        apply_url: "https://bb.org.bd",
        description: "Bangladesh Bank is recruiting Junior Officers specializing in Information Technology. Responsibilities include managing banking software, network security, and digital payment systems.",
        requirements: "B.Sc in Computer Science, Electrical Engineering, or Information Technology. Programming knowledge in Java/Python required.",
        source: "bdjobs",
        status: "active",
        is_featured: false,
        view_count: 8760
    },
    {
        id: "c004",
        title: "Sub-Assistant Engineer (Civil)",
        organization_id: 7,
        organization_name: "BUET",
        category_id: 8,
        vacancy: 12,
        job_type: "permanent",
        gender: "both",
        age_min: 18,
        age_max: 30,
        education_level: "Diploma",
        education_detail: "Diploma in Civil Engineering",
        experience_note: null,
        salary_display: "Tk. 16,000 — 38,640 (Grade-11)",
        salary_min: 16000,
        salary_max: 38640,
        salary_grade: "Grade-11",
        location: "Dhaka",
        district: "Dhaka",
        published_date: "2026-06-18",
        application_deadline: "2026-07-18",
        apply_via: "online",
        apply_url: "https://buet.ac.bd",
        description: "BUET (Bangladesh University of Engineering and Technology) is hiring Sub-Assistant Engineers for its infrastructure development projects on campus.",
        requirements: "Diploma in Civil Engineering from a recognized polytechnic institute. Must be proficient in AutoCAD.",
        source: "manual",
        status: "active",
        is_featured: false,
        view_count: 3200
    },
    {
        id: "c005",
        title: "Medical Officer",
        organization_id: 6,
        organization_name: "Ministry of Health",
        category_id: 6,
        vacancy: 500,
        job_type: "permanent",
        gender: "both",
        age_min: 21,
        age_max: 32,
        education_level: "MBBS",
        education_detail: "MBBS degree from a recognized medical college",
        experience_note: "Internship completion required",
        salary_display: "Tk. 22,000 — 53,060 (Grade-9)",
        salary_min: 22000,
        salary_max: 53060,
        salary_grade: "Grade-9",
        location: "Various Upazila Health Complexes",
        district: null,
        published_date: "2026-06-05",
        application_deadline: "2026-07-05",
        apply_via: "teletalk",
        apply_url: "http://mohfw.teletalk.com.bd",
        teletalk_code: "602",
        description: "The Ministry of Health and Family Welfare is recruiting 500 Medical Officers to be posted at Upazila Health Complexes across the country.",
        requirements: "MBBS degree with valid BMDC registration. Must have completed one-year internship by the application deadline.",
        source: "teletalk",
        status: "active",
        is_featured: true,
        view_count: 28900
    },
    {
        id: "c006",
        title: "Constable (Male)",
        organization_id: 4,
        organization_name: "Bangladesh Police",
        category_id: 4,
        vacancy: 2000,
        job_type: "permanent",
        gender: "male",
        age_min: 18,
        age_max: 22,
        education_level: "HSC",
        education_detail: "HSC or equivalent",
        experience_note: null,
        salary_display: "Tk. 9,000 — 21,800 (Grade-17)",
        salary_min: 9000,
        salary_max: 21800,
        salary_grade: "Grade-17",
        location: "Anywhere in Bangladesh",
        district: null,
        published_date: "2026-06-20",
        application_deadline: "2026-07-25",
        apply_via: "teletalk",
        apply_url: "http://police.teletalk.com.bd",
        teletalk_code: "703",
        description: "Bangladesh Police is recruiting 2000 Male Constables. This is a large-scale recruitment drive to strengthen law enforcement across the country. Physical fitness test and written exam will be conducted.",
        requirements: "HSC or equivalent pass. Height minimum 5'6\". Chest 30\"-32\". Physical fitness required.",
        source: "teletalk",
        status: "active",
        is_featured: true,
        view_count: 67200
    },
    {
        id: "c007",
        title: "Assistant Teacher (English)",
        organization_id: 5,
        organization_name: "Ministry of Education",
        category_id: 5,
        vacancy: 150,
        job_type: "permanent",
        gender: "both",
        age_min: 21,
        age_max: 35,
        education_level: "Masters",
        education_detail: "Master's in English or English Literature",
        experience_note: null,
        salary_display: "Tk. 16,000 — 38,640 (Grade-11)",
        salary_min: 16000,
        salary_max: 38640,
        salary_grade: "Grade-11",
        location: "Various Government Schools",
        district: null,
        published_date: "2026-05-25",
        application_deadline: "2026-06-30",
        apply_via: "online",
        apply_url: "https://moedu.gov.bd",
        description: "Ministry of Education is recruiting Assistant Teachers specialized in English for government high schools across Bangladesh.",
        requirements: "Master's degree in English with minimum 2nd class. B.Ed degree preferred.",
        source: "manual",
        status: "active",
        is_featured: false,
        view_count: 9800
    },
    {
        id: "c008",
        title: "Sergeant (Army)",
        organization_id: 3,
        organization_name: "Bangladesh Army",
        category_id: 3,
        vacancy: 100,
        job_type: "permanent",
        gender: "male",
        age_min: 17,
        age_max: 21,
        education_level: "SSC",
        education_detail: "SSC or equivalent with minimum GPA 3.50",
        experience_note: null,
        salary_display: "Tk. 15,000 — 34,500 (Grade-12)",
        salary_min: 15000,
        salary_max: 34500,
        salary_grade: "Grade-12",
        location: "Various Cantonments",
        district: null,
        published_date: "2026-06-12",
        application_deadline: "2026-07-12",
        apply_via: "online",
        apply_url: "https://army.mil.bd",
        description: "Bangladesh Army is recruiting Sergeants for various technical and non-technical roles. Candidates will go through physical fitness tests, written exams, and medical checks.",
        requirements: "SSC pass with minimum GPA 3.50. Must be physically fit. Height minimum 5'8\".",
        source: "manual",
        status: "active",
        is_featured: false,
        view_count: 34000
    },
    {
        id: "c009",
        title: "Station Master",
        organization_id: 8,
        organization_name: "Bangladesh Railway",
        category_id: 9,
        vacancy: 30,
        job_type: "permanent",
        gender: "both",
        age_min: 18,
        age_max: 30,
        education_level: "Bachelors",
        education_detail: "Bachelor's degree in any discipline",
        experience_note: null,
        salary_display: "Tk. 16,000 — 38,640 (Grade-11)",
        salary_min: 16000,
        salary_max: 38640,
        salary_grade: "Grade-11",
        location: "Various Railway Stations",
        district: null,
        published_date: "2026-06-08",
        application_deadline: "2026-07-08",
        apply_via: "online",
        apply_url: "https://railway.gov.bd",
        description: "Bangladesh Railway is hiring Station Masters for various railway stations. Responsibilities include managing station operations, train scheduling, and passenger services.",
        requirements: "Bachelor's degree in any discipline. Must pass railway recruitment board exam.",
        source: "manual",
        status: "active",
        is_featured: false,
        view_count: 5600
    },
    {
        id: "c010",
        title: "Data Entry Operator",
        organization_id: 7,
        organization_name: "BUET",
        category_id: 8,
        vacancy: 8,
        job_type: "temporary",
        gender: "both",
        age_min: 18,
        age_max: 30,
        education_level: "HSC",
        education_detail: "HSC with computer literacy",
        experience_note: "1 year experience preferred",
        salary_display: "Tk. 12,000 — 27,300 (Grade-14)",
        salary_min: 12000,
        salary_max: 27300,
        salary_grade: "Grade-14",
        location: "Dhaka",
        district: "Dhaka",
        published_date: "2026-06-22",
        application_deadline: "2026-07-15",
        apply_via: "online",
        apply_url: "https://buet.ac.bd",
        description: "BUET is looking for Data Entry Operators to assist in digitizing academic records and administrative documents.",
        requirements: "HSC pass with typing speed of 30 wpm in English and 25 wpm in Bangla. MS Office proficiency required.",
        source: "manual",
        status: "active",
        is_featured: false,
        view_count: 4500
    },
    {
        id: "c011",
        title: "Senior Staff Nurse",
        organization_id: 6,
        organization_name: "Ministry of Health",
        category_id: 6,
        vacancy: 350,
        job_type: "permanent",
        gender: "female",
        age_min: 18,
        age_max: 30,
        education_level: "Diploma",
        education_detail: "Diploma in Nursing Science and Midwifery",
        experience_note: null,
        salary_display: "Tk. 16,000 — 38,640 (Grade-11)",
        salary_min: 16000,
        salary_max: 38640,
        salary_grade: "Grade-11",
        location: "Various Government Hospitals",
        district: null,
        published_date: "2026-06-03",
        application_deadline: "2026-07-03",
        apply_via: "online",
        apply_url: "https://mohfw.gov.bd",
        description: "Ministry of Health is recruiting Senior Staff Nurses for government hospitals and health complexes nationwide. This is a full-time permanent position with government benefits.",
        requirements: "Diploma in Nursing Science and Midwifery from a recognized institution. Must have BNMC registration.",
        source: "manual",
        status: "active",
        is_featured: false,
        view_count: 12800
    },
    {
        id: "c012",
        title: "BCS 46th — Administration Cadre",
        organization_id: 2,
        organization_name: "Bangladesh Public Service Commission",
        category_id: 1,
        vacancy: 275,
        job_type: "permanent",
        gender: "both",
        age_min: 21,
        age_max: 30,
        education_level: "Bachelors",
        education_detail: "Bachelor's degree in any discipline",
        experience_note: null,
        salary_display: "Tk. 22,000 — 53,060 (Grade-9)",
        salary_min: 22000,
        salary_max: 53060,
        salary_grade: "Grade-9",
        location: "Anywhere in Bangladesh",
        district: null,
        published_date: "2026-06-01",
        application_deadline: "2026-07-10",
        apply_via: "teletalk",
        apply_url: "http://bpsc.teletalk.com.bd",
        teletalk_code: "450",
        description: "The 46th BCS Administration Cadre recruitment. Administration cadre officers serve as Assistant Commissioners and work in field-level administration across the country.",
        requirements: "Bachelor's degree with at least 2nd class. Age limit 21-30 years (32 for freedom fighter quota). Must be a Bangladeshi citizen.",
        source: "manual",
        status: "active",
        is_featured: true,
        view_count: 52000
    },
    {
        id: "c013",
        title: "Sub-Inspector (SI)",
        organization_id: 4,
        organization_name: "Bangladesh Police",
        category_id: 4,
        vacancy: 400,
        job_type: "permanent",
        gender: "both",
        age_min: 19,
        age_max: 27,
        education_level: "Bachelors",
        education_detail: "Bachelor's degree in any discipline",
        experience_note: null,
        salary_display: "Tk. 16,000 — 38,640 (Grade-11)",
        salary_min: 16000,
        salary_max: 38640,
        salary_grade: "Grade-11",
        location: "Anywhere in Bangladesh",
        district: null,
        published_date: "2026-06-25",
        application_deadline: "2026-07-30",
        apply_via: "teletalk",
        apply_url: "http://police.teletalk.com.bd",
        teletalk_code: "704",
        description: "Bangladesh Police is recruiting Sub-Inspectors. The SI is a key supervisory role in the police force, responsible for investigation, patrol, and law enforcement.",
        requirements: "Bachelor's degree. Height: male 5'6\"/female 5'4\". Chest: male 30\"-32\". Physical fitness test mandatory.",
        source: "teletalk",
        status: "active",
        is_featured: false,
        view_count: 18600
    },
    {
        id: "c014",
        title: "Ticket Collector",
        organization_id: 8,
        organization_name: "Bangladesh Railway",
        category_id: 9,
        vacancy: 50,
        job_type: "permanent",
        gender: "both",
        age_min: 18,
        age_max: 30,
        education_level: "HSC",
        education_detail: "HSC or equivalent",
        experience_note: null,
        salary_display: "Tk. 9,000 — 21,800 (Grade-17)",
        salary_min: 9000,
        salary_max: 21800,
        salary_grade: "Grade-17",
        location: "Various Railway Stations",
        district: null,
        published_date: "2026-06-08",
        application_deadline: "2026-07-08",
        apply_via: "online",
        apply_url: "https://railway.gov.bd",
        description: "Bangladesh Railway is recruiting Ticket Collectors (T.C.) for train services and station counters nationwide.",
        requirements: "HSC pass. Must be physically fit. Good communication skills required.",
        source: "manual",
        status: "active",
        is_featured: false,
        view_count: 7800
    },
    {
        id: "c015",
        title: "Pharmacist",
        organization_id: 6,
        organization_name: "Ministry of Health",
        category_id: 6,
        vacancy: 120,
        job_type: "permanent",
        gender: "both",
        age_min: 18,
        age_max: 30,
        education_level: "Diploma",
        education_detail: "Diploma in Pharmacy",
        experience_note: null,
        salary_display: "Tk. 12,000 — 27,300 (Grade-14)",
        salary_min: 12000,
        salary_max: 27300,
        salary_grade: "Grade-14",
        location: "Various Government Hospitals",
        district: null,
        published_date: "2026-06-14",
        application_deadline: "2026-07-14",
        apply_via: "online",
        apply_url: "https://mohfw.gov.bd",
        description: "Ministry of Health is recruiting Pharmacists for government hospital pharmacies. Responsibilities include dispensing medicines, inventory management, and patient counseling.",
        requirements: "Diploma in Pharmacy from a recognized institution. Must have Pharmacy Council registration.",
        source: "manual",
        status: "active",
        is_featured: false,
        view_count: 6200
    }
];

const CATEGORY_FILTERS = [
    { id: 0, name: "All", slug: "all" },
    ...CATEGORIES
];

const SORT_OPTIONS = [
    { value: "published_desc", label: "Newest First" },
    { value: "deadline_asc", label: "Deadline (Soonest)" },
    { value: "views_desc", label: "Most Viewed" },
];
